name: term
description: It's a library that controls the terminal, including the cursor, color, and text.
version: 0.1.0
repository: https://github.com/lollipopkit/term.dart

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
